spring.application.name=AirBnbClone

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/AirBnbDB
spring.datasource.username = postgres
spring.datasource.password=avanish7080
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

server.servlet.context-path=/api/v1

jwt.secretKey=asjbjkaneinaenodaodmnfcjssewdjiajlkdnjnf
deploy.env=development 
frontend.url=http://localhost:8080
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=whsec_ae43a9365af132164c9dcbbe0115de57ea92c71b4c63b7638a0e73a97bdcfa87
